---
id: 2023-09-16-matrk10-permanent_uri_and_dpu
base_name: permanent_uri_and_dpu
tags:
- CC-BY-4.0
presentation_date: '2023-09-16'
presentation_start_time:
presentation_end_time:
version: 2023.9.16.0
licenses: []
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1368
height: 768
source_code_uri:
author:
  markup_language: :markdown
  name: Yuya.Nishida.
  email:
  rubygems_user: nishidayuya
  slideshare_user:
  speaker_deck_user: nishidayuya
